matrix:
  include:
    - os: windows
      language: node_js
      node_js:
        - node
      addons:
        artifacts:
          working_dir: release

cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
    - flow-typed
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - yarn --ignore-engines

script:
  - yarn package-win
