matrix:
  include:
    - os: windows
      language: node_js
      node_js:
        - node
      addons:
        artifacts:
          working_dir: release
      script:
        - travis_wait 20 yarn package-win
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file:
          - release/*.exe
          - release/*.msi
        skip_cleanup: true
    - os: osx
      language: node_js
      node_js:
        - node
      addons:
        artifacts:
          working_dir: release
      script:
        - travis_wait 20 yarn package-mac
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file:
          - release/*.zip
          - release/*.dmg
        skip_cleanup: true

cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
#    - flow-typed
#    - $HOME/.cache/electron
#    - $HOME/.cache/electron-builder

install:
  - yarn --ignore-engines

